before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: tcYOeCjd+/ZUj/gquZ8F4KuwtohKpHp/XvIjpWPlXbi3icgNyEU8czfaoOeMo/Mu5PK//OkYQSkPghg6sJZh5+0zgYKD2pRJaSOCgWoULYrgk/UGQD6xoH637T2heLa8QliW2zpMqonVgOie1quncO14WFmUMr3eIKenti7Bn9Atk/qGij1KtekDB0JRya0NX8nrUJsfQ1JjSgHLQ2BnwFGQk6++MGsnCToieYEiPva0RwwNHoAYANzui/bNRZlm366JZSP7oZoGLJONMwSPMQ6BeJsHMiYkPsqVWdIc5csZ2j4x66tL/xhRQlYZ/Rvfa+h+lRE/F7iRj6+zsgBtzZQOqB7xU4OP/N8TdLchUw4wZWrXpqRsO1WpBMKe2ZWXmZFrEZoyf+wu3X+z5g+LznotF/vESG2JVFDtoqUL0ZHiY6O6X4g1v46p+d8AD+hCGgI+7Akl7NuPdwEBFzlS6M8k9MQxYJZ5oRb4PyXg0hhCJFifcCbMuEuomu7HS0xPu+21ZzpMikrCKzEiL67YmD8kuVJwwsAqRnDydu4L+yGsxoXcYhMekZ1JYCyoNRwUND/SyAkFIOAYCAEjIEwwc8ZEKBZ9w0cSRBOB+HMGqe5NhVq667hHns5UxLPovgmVhOxQmYtUoQ6GVfi6Gz4zrpFIBFLcpJdWMES1cSyeB2U= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
